### PR TITLE
backend: add controller / service tests split principle

### PR DESCRIPTION
**Pull request by divineforest**

### CODE REVIEW

**Review by dmlyapin — COMMENTED** [review]
But our previous vision was that we should always prefer controller / job / event tests under service tests. Controller / job / event tests stay on guard during any refactoring with service layer restructurings and this makes sense.

**Comment by andrey-kuznetsov-osome** [comment]
> refactoring with service layer restructurings and this makes sense

In my world, ideal controller tests should work like black box and use only API methods to modify and read data from service.
They should check status codes, success path, 404, 422 errors (maybe not all 422) and ACL

From other hand we have complex service level where services can call another services, enqueue jobs, perform multiple db operations depending on various input params. It is useful to check these cases via tests for services.

I can give you example where controllers tests become very complex and difficult to read -> document CRUD in Pablo
Document CRUD in Pablo has a great count of different scenarios, numerous side effects e.t.c It is really hard to place them into controllers.

**Comment by andrey-kuznetsov-osome** [comment]
It is a good way to define well structured entry point to complex service functionality like I did for example in ledger generator in Pablo or for reconciliation. So this entry point should not be changed during refactoring and tests should use it instead of call some nested service methods

**Comment by andrey-kuznetsov-osome** [comment]
Yet another reason to bring tests to service level is ability to call same service function from multiple places, for example from controllers, jobs, events ... I this case if you place tests in controller you will need to repeat them (or part of them) in jobs, events, e.t.c

**Comment by dmlyapin** [comment]
I agree that in some cases testing a service function is more clean and reasonable.

But I would prefer to keep top-level entity (controller / job / event) as a default way for testing like it is described here: 

https://github.com/OsomePteLtd/principles/blob/main/src/testing.md#strategy

> integration tests must be the majority
> unit tests can be used if needed only for the corner cases of the scenarios covered by integration tests

"Identical request/response" looks for me not enough for jumping to service level testing. Can we define the condition another way?

> It is a good way to define well structured entry point to complex service functionality like I did for example in ledger generator in Pablo or for reconciliation. So this entry point should not be changed during refactoring and tests should use it instead of call some nested service methods.

And maybe we should describe more clear what is "the main service function" which we can test.

**Review by dmlyapin — APPROVED** [review]

**Review by andrey-kuznetsov-osome — APPROVED** [review]

**Pull request merged**
